name: Build deocker images
on:
  push:
    branches: [ "devops" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch ✅
        uses: actions/checkout@v2

      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        run: |
          docker build --no-cache -t ${{ secrets.DOCKERHUB_USERNAME }}/manasu .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:latest
